[pytest]
pythonpath = .
filterwarnings =
    ignore::_pytest.warning_types.PytestUnknownMarkWarning

addopts =
;  ---- Основные настройки ----
    -v
    -s
    --maxfail=50
    --tb=short

;  ---- Playwright настройки ----
    --headed
    --browser chromium
    --slowmo 1500